restart_model: ensure user is logged in before permission check
this missing check is causing the following error message for unauthenticated
users:

    NoMethodError: undefined method `permission?' for nil:NilClass